name: CI

on:
    push:
        branches:
            - master
            - next
            - beta
            - alpha
            - "*.x"
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build_release:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: docker build --tag joa-mos/srp-docker-example .
            - run: docker tag joa-mos/srp-docker-example joamos/srp-docker-example
            - name: Login to ghcr.io docker registry
              run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u joa-mos --password-stdin
            - name: Login to docker.io docker registry
              run: echo ${{ secrets.DOCKERIO_PASSWORD }} | docker login -u joamos --password-stdin
            - name: Release
              uses: actions/setup-node@v2
              with:
                  cache: npm
            - run: npm ci --ignore-scripts
            - run: npx semantic-release-plus --debug
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
