name: CI

on:
    push:
        branches:
            - master
            - next
            - beta
            - alpha
            - "*.x"
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    build_release:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: docker build --tag ghcr.io/joa-mos/srp-docker-example .
            - name: Release
              uses: actions/setup-node@v2
              with:
                  cache: npm
            - run: npm ci
            - run: npx semantic-release-plus --debug
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DOCKER_USERNAME: joa-mos
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
